name: CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setup:
    name: Setup

    runs-on: [self-hosted, windows, server]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show Environment
        run: |
          $PSVersionTable
          $pwd
          Write-Host Path:
          $env:PATH
          Write-Host
          Write-Host whoami:
          whoami
          Write-Host
          Write-Host Default Environment Variables:
          Write-Host "CI: $env:CI"
          Write-Host "GITHUB_ACTION: $env:GITHUB_ACTION"
          Write-Host "GITHUB_ACTION_PATH: $env:GITHUB_ACTION_PATH"
          Write-Host "GITHUB_ACTION_REPOSITORY: $env:GITHUB_ACTION_REPOSITORY"
          Write-Host "GITHUB_ACTIONS: $env:GITHUB_ACTIONS"
          Write-Host "GITHUB_ACTOR: $env:GITHUB_ACTOR"
          Write-Host "GITHUB_ACTOR_ID: $env:GITHUB_ACTOR_ID"
          Write-Host "GITHUB_API_URL: $env:GITHUB_API_URL"
          Write-Host "GITHUB_BASE_REF: $env:GITHUB_BASE_REF"
          Write-Host "GITHUB_ENV: $env:GITHUB_ENV"
          Write-Host "GITHUB_EVENT_NAME: $env:GITHUB_EVENT_NAME"
          Write-Host "GITHUB_EVENT_PATH: $env:GITHUB_EVENT_PATH"
          Write-Host "GITHUB_GRAPHQL_URL: $env:GITHUB_GRAPHQL_URL"
          Write-Host "GITHUB_HEAD_REF: $env:GITHUB_HEAD_REF"
          Write-Host "GITHUB_JOB: $env:GITHUB_JOB"
          Write-Host "GITHUB_PATH: $env:GITHUB_PATH"
          Write-Host "GITHUB_REF: $env:GITHUB_REF"
          Write-Host "GITHUB_REF_NAME: $env:GITHUB_REF_NAME"
          Write-Host "GITHUB_REF_PROTECTED: $env:GITHUB_REF_PROTECTED"
          Write-Host "GITHUB_REF_TYPE: $env:GITHUB_REF_TYPE"
          Write-Host "GITHUB_REPOSITORY: $env:GITHUB_REPOSITORY"
          Write-Host "GITHUB_REPOSITORY_ID: $env:GITHUB_REPOSITORY_ID"
          Write-Host "GITHUB_REPOSITORY_OWNER: $env:GITHUB_REPOSITORY_OWNER"
          Write-Host "GITHUB_REPOSITORY_OWNER_ID: $env:GITHUB_REPOSITORY_OWNER_ID"
          Write-Host "GITHUB_RETENTION_DAYS: $env:GITHUB_RETENTION_DAYS"
          Write-Host "GITHUB_RUN_ATTEMPT: $env:GITHUB_RUN_ATTEMPT"
          Write-Host "GITHUB_RUN_ID: $env:GITHUB_RUN_ID"
          Write-Host "GITHUB_RUN_NUMBER: $env:GITHUB_RUN_NUMBER"
          Write-Host "GITHUB_SERVER_URL: $env:GITHUB_SERVER_URL"
          Write-Host "GITHUB_SHA: $env:GITHUB_SHA"
          Write-Host "GITHUB_STEP_SUMMARY: $env:GITHUB_STEP_SUMMARY"
          Write-Host "GITHUB_WORKFLOW: $env:GITHUB_WORKFLOW"
          Write-Host "GITHUB_WORKFLOW_REF: $env:GITHUB_WORKFLOW_REF"
          Write-Host "GITHUB_WORKFLOW_SHA: $env:GITHUB_WORKFLOW_SHA"
          Write-Host "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          Write-Host "RUNNER_ARCH: $env:RUNNER_ARCH"
          Write-Host "RUNNER_DEBUG: $env:RUNNER_DEBUG"
          Write-Host "RUNNER_NAME: $env:RUNNER_NAME"
          Write-Host "RUNNER_OS: $env:RUNNER_OS"
          Write-Host "RUNNER_TEMP: $env:RUNNER_TEMP"
          Write-Host "RUNNER_TOOL_CACHE: $env:RUNNER_TOOL_CACHE"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: pnpm install

      - name: Check for genlinx
        run: which genlinx

  build:
    name: Build

    runs-on: [self-hosted, windows, server]

    needs: [setup]

    steps:
      - name: Run Genlinx
        run: ./build.ps1

      - name: Upload build log only if failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-log
          path: ./*.build.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./Source/*.tko
            ./*.build.log

  release:
    name: Create Release

    runs-on: [self-hosted, windows, server]

    needs: [build]

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@d360fad3a42feca6462f72c97c165d60a02d4bf2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: ""
          release-count: "0"
          create-summary: true
          preset: "conventionalcommits"
          config-file-path: "./.changelogrc.json"

      - name: Create Github Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          # body_path: CHANGELOG.md
